In [74]:
# from __future__ import print_function, division
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import StratifiedKFold

In [75]:
data = pd.read_csv('final_restaurant_rating_data.csv')

data.head()

overall_rating  average_rating  average_rating_category  \
0             4.0             3.8                        0   
1             5.0             4.8                        1   
2             4.5             4.7                        1   
3             5.0             4.9                        1   
4             5.0             4.8                        1   

   is_travellors_choice  is_michellin  is_in_mall  walking_distance  \
0                     0             0         0.0             744.5   
1                     1             0         0.0             373.3   
2                     1             0         0.0             227.9   
3                     0             0         1.0             318.7   
4                     1             0         0.0            1399.9   

   region_bedok  region_bishan_toa_payoh  region_bugis_city_hall  ...  \
0           0.0                      0.0                     0.0  ...   
1           0.0                      0.0                     1.0  ...   
2           0.0                      0.0                     0.0  ...   
3           0.0                      0.0                     0.0  ...   
4           0.0                      0.0                     0.0  ...   

   operates_on_sat_or_sun  average_sentiment_score  img_uploaded_per_review  \
0                       1                 0.276577                 0.071429   
1                       1                 0.405635                 0.292683   
2                       1                 0.424801                 0.517665   
3                       1                 0.499230                 0.909465   
4                       1                 0.487331                 0.605475   

   proportion_of_positive_sentiment  nearest_train_line_color_blue  \
0                          0.857143                            1.0   
1                          0.982927                            0.0   
2                          0.971582                            0.0   
3                          0.987654                            0.0   
4                          0.977456                            0.0   

   nearest_train_line_color_green  nearest_train_line_color_others  \
0                             0.0                              0.0   
1                             0.0                              0.0   
2                             1.0                              0.0   
3                             0.0                              0.0   
4                             0.0                              0.0   

   nearest_train_line_color_purple  nearest_train_line_color_red  \
0                              0.0                           0.0   
1                              0.0                           0.0   
2                              0.0                           0.0   
3                              0.0                           0.0   
4                              1.0                           0.0   

   nearest_train_line_color_yellow  
0                              0.0  
1                              1.0  
2                              0.0  
3                              1.0  
4                              0.0  

[5 rows x 111 columns]

In [76]:
# data.columns.values

# ['overall_rating', 'average_rating', 'average_rating_category',
#        'is_travellors_choice', 'is_michellin', 'is_in_mall',
#        'walking_distance', 'region_bedok', 'region_bishan_toa_payoh',
#        'region_bugis_city_hall', 'region_bukit_merah_southern_islands',
#        'region_bukit_timah', 'region_changi', 'region_downtown',
#        'region_geylang', 'region_kallang', 'region_marina_bay',
#        'region_marina_centre', 'region_newton_orchard',
#        'region_north_region', 'region_northeast_region', 'region_novena',
#        'region_outram', 'region_paya_lebar_tampines_pasir_ris',
#        'region_queenstown', 'region_rochor', 'region_singapore_river',
#        'region_tanglin', 'region_west_region', 'has_price_category',
#        'price_category', 'above_median_dist_from_nearby_attraction',
#        'nearby_attraction_arab_street', 'nearby_attraction_boat_quay',
#        'nearby_attraction_chinatown', 'nearby_attraction_east_coast_park',
#        'nearby_attraction_garden', 'nearby_attraction_little_india',
#        'nearby_attraction_marina_bay', 'nearby_attraction_merlion_park',
#        'nearby_attraction_museum', 'nearby_attraction_observation',
#        'nearby_attraction_orchard_road', 'nearby_attraction_wildlife',
#        'nearby_attraction_nan',
#        'nearby_attraction_arab_street_above_median',
#        'nearby_attraction_boat_quay_above_median',
#        'nearby_attraction_chinatown_above_median',
#        'nearby_attraction_east_coast_park_above_median',
#        'nearby_attraction_garden_above_median',
#        'nearby_attraction_little_india_above_median',
#        'nearby_attraction_marina_bay_above_median',
#        'nearby_attraction_merlion_park_above_median',
#        'nearby_attraction_museum_above_median',
#        'nearby_attraction_observation_above_median',
#        'nearby_attraction_orchard_road_above_median',
#        'nearby_attraction_wildlife_above_median', 'meal_lunch',
#        'meal_dinner', 'meal_drinks', 'meal_breakfast', 'meal_brunch',
#        'meal_after_hours', 'has_meals', 'cuisine_arabic', 'cuisine_asian',
#        'cuisine_chinese', 'cuisine_european', 'cuisine_indian',
#        'cuisine_international', 'cuisine_italian', 'cuisine_japanese',
#        'has_cuisines', 'cuisine_north_american', 'cuisine_others',
#        'cuisine_sea', 'cuisine_south_american', 'feature_delivery',
#        'feature_reservations', 'feature_outdoor_seating',
#        'feature_seating', 'feature_highchairs_available',
#        'feature_digital_payments', 'feature_free_wifi',
#        'feature_cash_only', 'feature_wheelchair_accessible',
#        'feature_table_service', 'feature_live_music', 'has_features',
#        'feature_parking_avail', 'feature_alcohol_avail',
#        'feature_creditcard_avail', 'diet_vegetarian_friendly',
#        'diet_vegan_options', 'diet_gluten_free_options', 'diet_halal',
#        'total_operating_hours', 'num_of_days_open',
#        'average_daily_operating_hours', 'has_operating_hours',
#        'operates_on_weekends', 'operates_on_sat_or_sun',
#        'average_sentiment_score', 'img_uploaded_per_review',
#        'proportion_of_positive_sentiment',
#        'nearest_train_line_color_blue', 'nearest_train_line_color_green',
#        'nearest_train_line_color_others',
#        'nearest_train_line_color_purple', 'nearest_train_line_color_red',
#        'nearest_train_line_color_yellow']

In [77]:
# #Optimising Decision Tree
# # Create Decision Tree classifer object
# clf = DecisionTreeClassifier(criterion="entropy", max_depth=11)

# # Train Decision Tree Classifer
# clf = clf.fit(X_train,y_train)

# #Predict the response for test dataset
# y_pred = clf.predict(X_test)

# # Model Accuracy, how often is the classifier correct?
# print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
# print("Confusion Matrix:\n",metrics.confusion_matrix(y_test, y_pred))

In [78]:
#drop na row ('average_sentiment_score', 'img_uploaded_per_review', 'proportion_of_positive_sentiment')
data.dropna(inplace=True, subset=['average_sentiment_score'])
data.shape

(7191, 111)

In [79]:
#split dataset in features and target variable
# All features excluding ratings: 'overall_rating', 'average_rating', 'average_rating_category'
feature_cols = ['is_travellors_choice', 'is_michellin', 'is_in_mall',
       'walking_distance', 'region_bedok', 'region_bishan_toa_payoh',
       'region_bugis_city_hall', 'region_bukit_merah_southern_islands',
       'region_bukit_timah', 'region_changi', 'region_downtown',
       'region_geylang', 'region_kallang', 'region_marina_bay',
       'region_marina_centre', 'region_newton_orchard',
       'region_north_region', 'region_northeast_region', 'region_novena',
       'region_outram', 'region_paya_lebar_tampines_pasir_ris',
       'region_queenstown', 'region_rochor', 'region_singapore_river',
       'region_tanglin', 'region_west_region', 'has_price_category',
       'price_category', 'above_median_dist_from_nearby_attraction',
       'nearby_attraction_arab_street', 'nearby_attraction_boat_quay',
       'nearby_attraction_chinatown', 'nearby_attraction_east_coast_park',
       'nearby_attraction_garden', 'nearby_attraction_little_india',
       'nearby_attraction_marina_bay', 'nearby_attraction_merlion_park',
       'nearby_attraction_museum', 'nearby_attraction_observation',
       'nearby_attraction_orchard_road', 'nearby_attraction_wildlife',
       'nearby_attraction_nan',
       'nearby_attraction_arab_street_above_median',
       'nearby_attraction_boat_quay_above_median',
       'nearby_attraction_chinatown_above_median',
       'nearby_attraction_east_coast_park_above_median',
       'nearby_attraction_garden_above_median',
       'nearby_attraction_little_india_above_median',
       'nearby_attraction_marina_bay_above_median',
       'nearby_attraction_merlion_park_above_median',
       'nearby_attraction_museum_above_median',
       'nearby_attraction_observation_above_median',
       'nearby_attraction_orchard_road_above_median',
       'nearby_attraction_wildlife_above_median', 'meal_lunch',
       'meal_dinner', 'meal_drinks', 'meal_breakfast', 'meal_brunch',
       'meal_after_hours', 'has_meals', 'cuisine_arabic', 'cuisine_asian',
       'cuisine_chinese', 'cuisine_european', 'cuisine_indian',
       'cuisine_international', 'cuisine_italian', 'cuisine_japanese',
       'has_cuisines', 'cuisine_north_american', 'cuisine_others',
       'cuisine_sea', 'cuisine_south_american', 'feature_delivery',
       'feature_reservations', 'feature_outdoor_seating',
       'feature_seating', 'feature_highchairs_available',
       'feature_digital_payments', 'feature_free_wifi',
       'feature_cash_only', 'feature_wheelchair_accessible',
       'feature_table_service', 'feature_live_music', 'has_features',
       'feature_parking_avail', 'feature_alcohol_avail',
       'feature_creditcard_avail', 'diet_vegetarian_friendly',
       'diet_vegan_options', 'diet_gluten_free_options', 'diet_halal',
       'total_operating_hours', 'num_of_days_open',
       'average_daily_operating_hours', 'has_operating_hours',
       'operates_on_weekends', 'operates_on_sat_or_sun',
       'nearest_train_line_color_blue', 'nearest_train_line_color_green',
       'nearest_train_line_color_others',
       'nearest_train_line_color_purple', 'nearest_train_line_color_red',
       'nearest_train_line_color_yellow']
X = data[feature_cols] # Features
y = data["average_rating_category"] # Target variable

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=2022, stratify = y)

skf = StratifiedKFold(n_splits=5, random_state=2022, shuffle=True)

for train_index, test_index in skf.split(X, y):
  X_train, X_test = X.iloc[train_index], X.iloc[test_index]
  y_train, y_test = y.iloc[train_index], y.iloc[test_index]

# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n",metrics.confusion_matrix(y_test, y_pred))
print("ROC AUC Score:",metrics.roc_auc_score(y_test, y_pred))

Accuracy: 0.5744089012517385
Confusion Matrix:
 [[447 309]
 [303 379]]
ROC AUC Score: 0.5734941581715776


In [80]:
#split dataset in features and target variable
#regions
feature_cols = ['region_bedok', 'region_bishan_toa_payoh',
       'region_bugis_city_hall', 'region_bukit_merah_southern_islands',
       'region_bukit_timah', 'region_changi', 'region_downtown',
       'region_geylang', 'region_kallang', 'region_marina_bay',
       'region_marina_centre', 'region_newton_orchard',
       'region_north_region', 'region_northeast_region', 'region_novena',
       'region_outram', 'region_paya_lebar_tampines_pasir_ris',
       'region_queenstown', 'region_rochor', 'region_singapore_river',
       'region_tanglin', 'region_west_region']
X = data[feature_cols] # Features
y = data["average_rating_category"] # Target variable

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=2022)

StratifiedKFold(n_splits=5, random_state=2022, shuffle=True)

for train_index, test_index in skf.split(X, y):
  X_train, X_test = X.iloc[train_index], X.iloc[test_index]
  y_train, y_test = y.iloc[train_index], y.iloc[test_index]

# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n",metrics.confusion_matrix(y_test, y_pred))
print("ROC AUC Score:",metrics.roc_auc_score(y_test, y_pred))

Accuracy: 0.5737134909596662
Confusion Matrix:
 [[529 227]
 [386 296]]
ROC AUC Score: 0.5668765225216839


In [81]:
#split dataset in features and target variable
# some selected features
feature_cols = ['is_travellors_choice', 'is_michellin', 'is_in_mall', 'has_price_category',
                'price_category', 'walking_distance']
X = data[feature_cols] # Features
y = data["average_rating_category"] # Target variable

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=2022)

StratifiedKFold(n_splits=5, random_state=2022, shuffle=True)

for train_index, test_index in skf.split(X, y):
  X_train, X_test = X.iloc[train_index], X.iloc[test_index]
  y_train, y_test = y.iloc[train_index], y.iloc[test_index]

# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n",metrics.confusion_matrix(y_test, y_pred))
print("ROC AUC Score:",metrics.roc_auc_score(y_test, y_pred))

Accuracy: 0.5605006954102921
Confusion Matrix:
 [[480 276]
 [356 326]]
ROC AUC Score: 0.5564632500116371


In [82]:
#split dataset in features and target variable
# nearby attractions
feature_cols = ['above_median_dist_from_nearby_attraction',
       'nearby_attraction_arab_street', 'nearby_attraction_boat_quay',
       'nearby_attraction_chinatown', 'nearby_attraction_east_coast_park',
       'nearby_attraction_garden', 'nearby_attraction_little_india',
       'nearby_attraction_marina_bay', 'nearby_attraction_merlion_park',
       'nearby_attraction_museum', 'nearby_attraction_observation',
       'nearby_attraction_orchard_road', 'nearby_attraction_wildlife',
       'nearby_attraction_nan',
       'nearby_attraction_arab_street_above_median',
       'nearby_attraction_boat_quay_above_median',
       'nearby_attraction_chinatown_above_median',
       'nearby_attraction_east_coast_park_above_median',
       'nearby_attraction_garden_above_median',
       'nearby_attraction_little_india_above_median',
       'nearby_attraction_marina_bay_above_median',
       'nearby_attraction_merlion_park_above_median',
       'nearby_attraction_museum_above_median',
       'nearby_attraction_observation_above_median',
       'nearby_attraction_orchard_road_above_median',
       'nearby_attraction_wildlife_above_median']
X = data[feature_cols] # Features
y = data["average_rating_category"] # Target variable

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=2022)

StratifiedKFold(n_splits=5, random_state=2022, shuffle=True)

for train_index, test_index in skf.split(X, y):
  X_train, X_test = X.iloc[train_index], X.iloc[test_index]
  y_train, y_test = y.iloc[train_index], y.iloc[test_index]

# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n",metrics.confusion_matrix(y_test, y_pred))
print("ROC AUC Score:",metrics.roc_auc_score(y_test, y_pred))

Accuracy: 0.5709318497913769
Confusion Matrix:
 [[479 277]
 [340 342]]
ROC AUC Score: 0.5675320796288538


In [83]:
#split dataset in features and target variable
# meals & cuisines
feature_cols = ['meal_lunch',
       'meal_dinner', 'meal_drinks', 'meal_breakfast', 'meal_brunch',
       'meal_after_hours', 'has_meals', 'cuisine_arabic', 'cuisine_asian',
       'cuisine_chinese', 'cuisine_european', 'cuisine_indian',
       'cuisine_international', 'cuisine_italian', 'cuisine_japanese',
       'has_cuisines', 'cuisine_north_american', 'cuisine_others',
       'cuisine_sea', 'cuisine_south_american']
X = data[feature_cols] # Features
y = data["average_rating_category"] # Target variable

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=2022)

StratifiedKFold(n_splits=5, random_state=2022, shuffle=True)

for train_index, test_index in skf.split(X, y):
  X_train, X_test = X.iloc[train_index], X.iloc[test_index]
  y_train, y_test = y.iloc[train_index], y.iloc[test_index]

# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n",metrics.confusion_matrix(y_test, y_pred))
print("ROC AUC Score:",metrics.roc_auc_score(y_test, y_pred))

Accuracy: 0.5598052851182197
Confusion Matrix:
 [[637 119]
 [514 168]]
ROC AUC Score: 0.5444634517215161


In [84]:
#split dataset in features and target variable
# restaurants with 'special' features
feature_cols = ['feature_outdoor_seating',
       'feature_seating', 'feature_highchairs_available',
       'feature_digital_payments', 'feature_free_wifi',
       'feature_cash_only', 'feature_wheelchair_accessible',
       'feature_table_service', 'feature_live_music', 'has_features',
       'feature_parking_avail', 'feature_alcohol_avail',
       'feature_creditcard_avail']
X = data[feature_cols] # Features
y = data["average_rating_category"] # Target variable

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=2022)

StratifiedKFold(n_splits=5, random_state=2022, shuffle=True)

for train_index, test_index in skf.split(X, y):
  X_train, X_test = X.iloc[train_index], X.iloc[test_index]
  y_train, y_test = y.iloc[train_index], y.iloc[test_index]

# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n",metrics.confusion_matrix(y_test, y_pred))
print("ROC AUC Score:",metrics.roc_auc_score(y_test, y_pred))

Accuracy: 0.5702364394993046
Confusion Matrix:
 [[668  88]
 [530 152]]
ROC AUC Score: 0.5532358919455693


In [85]:
#split dataset in features and target variable
# dietary options
feature_cols = ['diet_vegetarian_friendly',
       'diet_vegan_options', 'diet_gluten_free_options', 'diet_halal']
X = data[feature_cols] # Features
y = data["average_rating_category"] # Target variable

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=2022)

StratifiedKFold(n_splits=5, random_state=2022, shuffle=True)

for train_index, test_index in skf.split(X, y):
  X_train, X_test = X.iloc[train_index], X.iloc[test_index]
  y_train, y_test = y.iloc[train_index], y.iloc[test_index]

# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n",metrics.confusion_matrix(y_test, y_pred))
print("ROC AUC Score:",metrics.roc_auc_score(y_test, y_pred))

Accuracy: 0.5813630041724618
Confusion Matrix:
 [[673  83]
 [519 163]]
ROC AUC Score: 0.56460728638148


In [86]:
#split dataset in features and target variable
# operating hours
feature_cols = ['total_operating_hours', 'num_of_days_open',
       'average_daily_operating_hours', 'has_operating_hours',
       'operates_on_weekends', 'operates_on_sat_or_sun']
X = data[feature_cols] # Features
y = data["average_rating_category"] # Target variable

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=2022)

StratifiedKFold(n_splits=5, random_state=2022, shuffle=True)

for train_index, test_index in skf.split(X, y):
  X_train, X_test = X.iloc[train_index], X.iloc[test_index]
  y_train, y_test = y.iloc[train_index], y.iloc[test_index]

# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n",metrics.confusion_matrix(y_test, y_pred))
print("ROC AUC Score:",metrics.roc_auc_score(y_test, y_pred))

Accuracy: 0.5751043115438108
Confusion Matrix:
 [[648 108]
 [503 179]]
ROC AUC Score: 0.5598031001256808


In [87]:
#split dataset in features and target variable
feature_cols = ['nearest_train_line_color_blue', 'nearest_train_line_color_green',
       'nearest_train_line_color_others',
       'nearest_train_line_color_purple', 'nearest_train_line_color_red',
       'nearest_train_line_color_yellow']
X = data[feature_cols] # Features
y = data["average_rating_category"] # Target variable

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=2022)

StratifiedKFold(n_splits=5, random_state=2022, shuffle=True)

for train_index, test_index in skf.split(X, y):
  X_train, X_test = X.iloc[train_index], X.iloc[test_index]
  y_train, y_test = y.iloc[train_index], y.iloc[test_index]

# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n",metrics.confusion_matrix(y_test, y_pred))
print("ROC AUC Score:",metrics.roc_auc_score(y_test, y_pred))

Accuracy: 0.5625869262865091
Confusion Matrix:
 [[653 103]
 [526 156]]
ROC AUC Score: 0.5462478083445825
